### PR TITLE
Fix up support for booleans

### LINKED ISSUE #34: Boolean return support
I want to be able to compile the following
```
boolean return_true();
```

Currently I'm getting the error:
```
87 |     <u8 as uniffi::support::ViaFfi>::into_ffi_value(_retval)
   |                                                     ^^^^^^^ expected `u8`, found `bool`
```

### PR DESCRIPTION
**Pull request by rfk**
This should fix #34 and #35, although I've only added tests for the former.

There's a bunch of `pub`-changes here which I will explain in a comment, and which I'm not wedded to if they don't seem worthwhile. But I discovered a neat thing that I wanted to try out for the rust scaffolding.

### CODE REVIEW

File: uniffi/src/scaffolding.rs [hunk 1]
```diff
@@ -42,41 +39,38 @@ mod filters {
...
-            TypeReference::Enum(_) => "u32".to_string(),
-            TypeReference::Record(_) => "ffi_support::ByteBuffer".to_string(),
-            TypeReference::Optional(_) => "ffi_support::ByteBuffer".to_string(),
+            // Objects don't currently impl `ViaFfi`.
             TypeReference::Object(_) => "u64".to_string(),
-            _ => type_rs(type_)?,
+            _ => format!(
+              "<{} as uniffi::support::ViaFfi>::Value",
+              type_rs(type_)?,
+            ),
```
Comment (rfk) [inline uniffi/src/scaffolding.rs:62]: I discovered that you can use the associated types of a trait in the type signature of a function. Expressing it like this means we don't have to repeat the big list of "rust type X maps to FFI type Y" here when generating the scaffolding, we can just look up the mapping on the `ViaFfi` trait.

I like it, but some downsides of this approach:

* The generating rust scaffolding is a bit more visually complex; I would argue that it's actually easier to *understand* because you don't have to account for the mapping between Rust and C types, but it's definitely extra syntax noise.
* This only works if the corresponding rust types are public, since they appear in the type signature of a public function. Hence all the additions of `pub` in the examples. But TBH I think it's reasonable to insist that these types be marked `pub` because they are part of your public API.

If you don't like this, I can revert the change can go back to a big `match` statement like we had here before, but I figured I'd try it out.

Comment (eoger) [reply uniffi/src/scaffolding.rs:62]: This is the kind of magic that I like, I'll take 1 source of truth over 3, nice cleanup :)

**Comment by rfk** [comment]
> This is the kind of magic that I like

TBH I couldn't quite believe this Just Worked (tm) when I tried it the first time, the richness of rust's type system continues to impress me.
