### PR TITLE
Fix Kotlin error handling in async functions

### LINKED ISSUE #1611: Cannot return struct using Result in async function
Here is a [minimal repro](https://github.com/mozilla/uniffi-rs/compare/main...richardhuaaa:uniffi-rs:repro-async-error?expand=1) (only tested against Kotlin). It seems that async functions can return `Result<Primitive, Error>` or `Option<Arc<Struct>>`, but not `Result<Arc<Struct>, Error>`. Sync functions can return `Result<Arc<Struct>, Error>` without issue.

As the repro shows, if the struct is successfully returned, there is no issue. However, if an error is returned, we get a null pointer exception:

```
init time: 347ms
fallible function (with result): 3ms ... ok
Jun 20, 2023 12:35:16 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback uniffi.fixture.futures.UniFfiFutureCallbackHandlerTypeMegaphone_TypeMyError@7d7c05fa threw the following exception
java.lang.NullPointerException: Parameter specified as non-null is null: method uniffi.fixture.futures.UniFfiFutureCallbackHandlerTypeMegaphone_TypeMyError.invoke, parameter returnValue
        at uniffi.fixture.futures.UniFfiFutureCallbackHandlerTypeMegaphone_TypeMyError.invoke(uniffi_futures.kt)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:579)
        at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:610)
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:415)
        at com.sun.jna.Function.invoke(Function.java:361)
        at com.sun.jna.Function.invoke(Function.java:315)
        at com.sun.jna.CallbackReference$NativeFunctionHandler.invoke(CallbackReference.java:738)
        at jdk.proxy4/jdk.proxy4.$Proxy26.invoke(Unknown Source)
        at uniffi.fixture.futures.UniFfiForeignExecutorCallback$invoke$1.invokeSuspend(uniffi_futures.kt:945)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at Test_futures.<init>(test_futures.kts:15)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.evalWithConfigAndOtherScriptsResults(BasicJvmScriptEvaluator.kt:105)
        at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke$suspendImpl(BasicJvmScriptEvaluator.kt:47)
        at kotlin.script.experimental.jvm.BasicJvmScriptEvaluator.invoke(BasicJvmScriptEvaluator.kt)
        at org.jetbrains.kotlin.scripting.compiler.plugin.AbstractScriptEvaluationExtension$doEval$1.invokeSuspend(AbstractScriptEvaluationExtension.kt:156)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at kotlin.script.experimental.impl.RunSuspendKt.internalScriptingRunSuspend(runSuspend.kt:19)
        at org.jetbrains.kotlin.scripting.compiler.plugin.AbstractScriptEvaluationExtension.doEval(AbstractScriptEvaluationExtension.kt:135)
        at org.jetbrains.kotlin.scripting.compiler.plugin.AbstractScriptEvaluationExtension.eval(AbstractScriptEvaluationExtension.kt:122)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:114)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:43)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:180)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit$default(CLITool.kt:178)
        at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:167)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler$Companion.main(K2JVMCompiler.kt:251)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.main(K2JVMCompiler.kt)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.jetbrains.kotlin.preloading.Preloader.run(Preloader.java:87)
        at org.jetbrains.kotlin.preloading.Preloader.main(Preloader.java:44)
 ```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-291)
┆Issue Number: UNIFFI-291

### PR DESCRIPTION
**Pull request by mhammond**
Seems like it probably fixes #1611 but I'm really not sure what I am doing :) cc @Hywan, does this look OK to you?

### CODE REVIEW

File: uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt [hunk 1]
```diff
@@ -26,12 +26,12 @@ internal interface UniFfiFutureCallback{{ callback_param|ffi_type_name }} : com.
 
 internal class {{ result_type|future_callback_handler }}(val continuation: {{ result_type|future_continuation_type }})
     : UniFfiFutureCallback{{ callback_param|ffi_type_name }} {
-    override fun invoke(_callbackData: USize, returnValue: {{ callback_param|ffi_type_name_by_value }}, callStatus: RustCallStatus.ByValue) {
```
Comment (Hywan) [inline uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt:29]: Hmm. The definition of `callback_param` looks wrong.

In [`AsyncTypes.py`](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/python/templates/AsyncTypes.py), we have this for the argument:

```python
        {%- match result_type.return_type -%}
        {%- when Some(return_type) -%}
        {{ return_type.ffi_type().borrow()|ffi_type_name }}
        {%- when None -%}
        ctypes.c_uint8
        {%- endmatch -%}
```

No result type generates `ctypes.c_uint8` which seems to accept a null value.

In [`AsyncType.swift`](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/AsyncTypes.swift):

```swift
 returnValue: {{ result_type.future_callback_param().borrow()|ffi_type_name }},
```

which fallbacks to `Ffi::Uint8`, which seems to accept a null value.

The rest is ensured by the `when Some(return_type)` dance.

Either you change how `callback_param` is defined, _or_ I would say this patch is valid :-p. I'm really surprised that it works with Swift. Didn't dig that much though.

**Review by Hywan — APPROVED** [review]

File: uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt (hunk 1 above)
Comment (bendk) [reply uniffi_bindgen/src/bindings/kotlin/templates/AsyncTypes.kt:29]: This seems right to me.  The return FFI type is a pointer, since the parameter is an `Arc<>`.  Errors get returned through a out-param and when the Rust function returns an error it needs to return some placeholder value for the pointer, which is `null`.  This is different than either a void return or an `Option<Arc<>>`.

`checkCallStatus()` will throw an exception in the error case, so `returnValue` will never actually be touched.  I haven't looked at the Swift code, but maybe Swift allows the null pointer as long as it's not accessed.

**Review by bendk — APPROVED** [review]
