### PR TITLE
Fixes clippy for consumers

### LINKED ISSUE #254: Fix clippy for generated code
Right now running `cargo clippy` in a project that uses `uniffi` results in a few clippy errors, we could either try to fix them, or just disable clippy warnings in any spot that we can't cleanly make it happy. (We could also just say that consumers can deal with it as well if it's not worth our time)

Here is a long and ugly log from running clippy with the nimbus SDK:
```rust
/Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:343:3
    |
343 | ) -> () {
    |   ^^^^^ help: remove the `-> ()`
    |
    = note: `#[warn(clippy::unused_unit)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: returning the result of a `let` binding from a block
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:357:9
    |
352 | /         let _retval = Experiments::opt_in_with_branch(
353 | |             obj,
354 | |             <String as uniffi::ViaFfi>::try_lift(experiment_slug).unwrap(),
355 | |             <String as uniffi::ViaFfi>::try_lift(branch).unwrap(),
356 | |         );
    | |__________- unnecessary `let` binding
357 |           _retval
    |           ^^^^^^^
    |
    = note: `#[warn(clippy::let_and_return)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly
    |
352 |         
353 |         Experiments::opt_in_with_branch(
354 |             obj,
355 |             <String as uniffi::ViaFfi>::try_lift(experiment_slug).unwrap(),
356 |             <String as uniffi::ViaFfi>::try_lift(branch).unwrap(),
357 |         )
    |

warning: unneeded unit return type
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:365:3
    |
365 | ) -> () {
    |   ^^^^^ help: remove the `-> ()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: returning the result of a `let` binding from a block
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:378:9
    |
374 | /         let _retval = Experiments::opt_out(
375 | |             obj,
376 | |             <String as uniffi::ViaFfi>::try_lift(experiment_slug).unwrap(),
377 | |         );
    | |__________- unnecessary `let` binding
378 |           _retval
    |           ^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly
    |
374 |         
375 |         Experiments::opt_out(
376 |             obj,
377 |             <String as uniffi::ViaFfi>::try_lift(experiment_slug).unwrap(),
378 |         )
    |

warning: unneeded unit return type
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:383:63
    |
383 | pub extern "C" fn nimbus_Experiments_opt_out_all(handle: u64) -> () {
    |                                                               ^^^^^ help: remove the `-> ()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

warning: returning the result of a `let` binding from a block
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:393:9
    |
392 |         let _retval = Experiments::opt_out_all(obj);
    |         -------------------------------------------- unnecessary `let` binding
393 |         _retval
    |         ^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
help: return the expression directly
    |
392 |         
393 |         Experiments::opt_out_all(obj)
    |

warning: unneeded unit return type
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:401:3
    |
401 | ) -> () {
    |   ^^^^^ help: remove the `-> ()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit

/ pub unsafe extern "C" fn ffi_nimbus_string_alloc_from(
28 | |     cstr: *const std::os::raw::c_char,
29 | |     err: &mut uniffi::deps::ffi_support::ExternError,
30 | | ) -> *mut std::os::raw::c_char {
...  |
44 | |     })
45 | | }
   | |_^
   |
   = note: `#[warn(clippy::missing_safety_doc)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc

warning: unsafe function's docs miss `# Safety` section
  --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:52:1
   |
52 | / pub unsafe extern "C" fn ffi_nimbus_string_free(cstr: *mut std::os::raw::c_char) {
53 | |     // We deliberately don't check the `Result` here, so that callers don't need to pass an out `err`.
54 | |     // There was nothing for us to free in the failure case anyway, so no point in propagating the error.
55 | |     let s = <String as uniffi::ViaFfi>::try_lift(cstr);
56 | |     drop(s)
57 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_safety_doc

warning: passing a unit value to a function
   --> /Users/teshaq/code/nimbus-sdk/experiments/target/debug/build/experiments-e671f8ff694721e7/out/nimbus.uniffi.rs:408:12
    |
408 |         Ok(_retval)
    |            ^^^^^^^
    |
    = note: `#[warn(clippy::unit_arg)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg
help: if you intended to pass a unit value, use a unit literal instead
    |
408 |         Ok(())
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1703)

### PR DESCRIPTION
**Pull request by tarikeshaq**
fixes #254 

Adds `#[allow(clippy::all)]` in all generated functions.

A WAY nicer way to do this is to add `#![allow(clippy::all)]` but unfortunately that doesn't work because of https://github.com/rust-lang/rfcs/issues/752, although I would be happy if there is a different way to disable clippy on the whole generated file without asking the consumer to do so.

Note: I did not add the `#[allow(clippy::all)]` for anything other than the functions purely because they didn't complain, I'd be happy to go around doing that if we need to.

I also fixed some clippy errors that popped up (not sure if it's because I updated to `1.46`)

### CODE REVIEW

File: uniffi_bindgen/src/lib.rs [hunk 1]
```diff
@@ -89,6 +89,9 @@
 //! to load and use the compiled rust code via its C-compatible FFI.
 //!
 
+#![warn(rust_2018_idioms)]
```
Comment (tarikeshaq) [inline uniffi_bindgen/src/lib.rs:92]: The compiler started telling me that the `#![warn(rust_2018_idioms)]` is ignored if it's not at the crate level, so I moved those here

File: uniffi_bindgen/src/templates/RustString.rs [hunk 2]
```diff
@@ -32,6 +33,9 @@ pub unsafe extern "C" fn {{ ci.ffi_string_alloc_from().name() }}(cstr: *const st
 /// The argument *must* be a uniquely-owned pointer previously obtained from a call
 /// into the rust code that returned a string.
 ///
+/// # Safety
+/// In order to free the string, Rust takes ownership of a raw pointer
+/// which is an unsafe operation
```
Comment (rfk) [inline uniffi_bindgen/src/templates/RustString.rs:38]: micro-nit: A recent pet peeve of my are `# Safety` comments that point out where the unsafety is coming from, but don't tell you what you need to do to ensure it's safe. Could you please move the preceding sentence about how this must be a uniquely-owned blah-blah inside the safety block?

**Review by rfk — APPROVED** [review]
LGTM, thanks! I think it would be better to generate clippy-compliant code, but that's a much bigger change that is probably not a good use of our time short-term. Do you think it would be worth a follow-up bug?
